language: java
install: true
script:
  - ./gradlew clean check
before_deploy:
  - sed -i 's/VERSION_NUMBER/'$(./gradlew xrpc:properties | grep "version:" | awk '{print $2}')'/g' .travis/bintray_descriptor.json
  - sed -i 's/RELEASE_DATE/'$(date +%Y-%m-%d)'/g' .travis/bintray_descriptor.json
  - ./gradlew generatePomFileForXrpcMavenPublication publishToMavenLocal
deploy:
  - provider: bintray
    edge:
      branch: v1.8.47
    skip_cleanup: true
    file: .travis/bintray_descriptor.json
    user: $BINTRAY_USERNAME
    key: $BINTRAY_KEY
    on:
      branch: master
      tags: true
